export const LETTERS_TO_FINGERS: {[letters: string]: string} = {
  '/שז': 'left-pinky',
  "'דס": 'left-ring-finger',
  קגב: 'left-middle-finger',
  רכהנעא: 'left-index-finger',
  ' ': 'left-thumb',
  וחצמיט: 'right-index-finger',
  ןלת: 'right-middle-finger',
  םךץ: 'right-ring-finger',
  'פף.],[\\': 'right-pinky',
};

export const LETTER_TO_KEYCAP: {[letter: string]: string} = {
  ז: 'keycap-z',
  פ: 'keycap-pe',
  '/': 'keycap-q',
  ',': 'keycap-comma',
  ף: 'keycap-pe-sofit',
  ש: 'keycap-shin',
  '.': 'keycap-dot',
  ץ: 'keycap-tzadik-sofit',
  ס: 'keycap-samech',
  ם: 'keycap-mem-sofit',
  "'": 'keycap-geresh',
  ך: 'keycap-kaf-sofit',
  ד: 'keycap-dalet',
  ת: 'keycap-taf',
  ב: 'keycap-bet',
  ן: 'keycap-noon-sofit',
  ק: 'keycap-koof',
  ל: 'keycap-lamed',
  ג: 'keycap-gimel',
  ה: 'keycap-hei',
  ר: 'keycap-resh',
  כ: 'keycap-kaf',
  צ: 'keycap-tzadik',
  ו: 'keycap-vav',
  ח: 'keycap-het',
  נ: 'keycap-noon',
  א: 'keycap-alef',
  ע: 'keycap-ayin',
  מ: 'keycap-mem',
  י: 'keycap-yod',
  ט: 'keycap-tet',
  ' ': 'keycap-spacebar',
};
